spring:
  application:
    name: cloud-client

some.property: "app specific overridden value"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
server:
  port: 7777
